export enum Role {
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN',
  ROLE_USER = 'ROLE_USER',
  ROLE_SALES = 'ROLE_SALES',
  ROLE_CS = 'ROLE_CS',
  ROLE_MERCHANT = 'ROLE_MERCHANT',
}
